export const ADDRESS_REQUEST = 'ADDRESS_REQUEST';
export const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS';
export const ADDRESS_FAILURE = 'ADDRESS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const PRESENSI_REQUEST = 'PRESENSI_REQUEST';
export const PRESENSI_SUCCESS = 'PRESENSI_SUCCESS';
export const PRESENSI_FAILURE = 'PRESENSI_FAILURE';

export const DATANG_REQUEST = 'DATANG_REQUEST';
export const DATANG_SUCCESS = 'DATANG_SUCCESS';
export const DATANG_FAILURE = 'DATANG_FAILURE';

export const PULANG_REQUEST = 'PULANG_REQUEST';
export const PULANG_SUCCESS = 'PULANG_SUCCESS';
export const PULANG_FAILURE = 'PULANG_FAILURE';

export const TIME_REQUEST = 'TIME_REQUEST';
export const TIME_SUCCESS = 'TIME_SUCCESS';
export const TIME_FAILURE = 'TIME_FAILURE';

export const HISTORY_REQUEST = 'HISTORY_REQUEST';
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS';
export const HISTORY_FAILURE = 'HISTORY_FAILURE';

export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';

export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAILURE = 'LOCATION_FAILURE';

export const IP_REQUEST = 'IP_REQUEST';
export const IP_SUCCESS = 'IP_SUCCESS';
export const IP_FAILURE = 'IP_FAILURE';


export const mapApi = 'pk.eyJ1IjoibjNybzU1NSIsImEiOiJja3Nib2xycWIwOHJqMnRxazdmeHR1Zm81In0.CVAlhyoxkiRsVq8U4khzuQ'

export const BASE_URL = 'http://api-presensi.umrah.ac.id'